import { TAppUserWithTimestamps } from "../../types/types/app.user.type";

export const appUsers: TAppUserWithTimestamps[] = [
    {
        id: 'usr_56913465891340',
        email: 'user1@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'One',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'usr_56913465891350',
        email: 'user2@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'Two',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'usr_56913465891360',
        email: 'user3@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'Three',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
        {
        id: 'usr_56913465891370',
        email: 'user4@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'Four',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
        {
        id: 'usr_56913465891380',
        email: 'user5@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'Five',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
        {
        id: 'usr_56913465891390',
        email: 'user6@mail.com',
        password: 'password',
        firstName: 'User',
        lastName: 'Six',
        avatarUrl: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];